### ISSUE TITLE
Stalk Alignment

### ISSUE THREAD

**Issue by 0x3333** [majarspeed/Unklicky#1]
Is it normal to the stalk be miss aligned?

It’s the effect of the repulsing magnet is not aligned. 

Is this expected ?

![C3085232-E628-4B7A-8D0F-A277189593EB](https://user-images.githubusercontent.com/289289/160727807-e81017e4-6f7a-4214-ad55-756874aeb48e.jpeg)

Edit: it work as expected, like a spring. But I don’t know if it is supposed to be this way.

**Comment by majarspeed** [comment]
there should be a tight enough fit on the screw to keep it straight. I have created some tighter tolerance pins and waiting for feedback.

**Comment by 0x3333** [comment]
I tried the -0.1 and -0.2 same situation, just a little better.

![image](https://user-images.githubusercontent.com/289289/160931802-752c4251-e56b-44d1-9b1b-95582d32b1e0.png)
![image](https://user-images.githubusercontent.com/289289/160931824-6eee6370-736b-4c63-a610-445e2c86b60c.png)

What is the supposed orientation of the small magnet? Near the center or the border?

**Comment by majarspeed** [comment]
Small magnet should be to the inside.

**Comment by 0x3333** [comment]
Well, looks like the missing magnets have an effect aligning the stalk.
