### ISSUE TITLE
Support on the "slim" version to thin

### ISSUE THREAD

**Issue by Exerqtor** [majarspeed/Unklicky#11]
Just printed the "slim" version, and it came out great except that the chamfer on the supported partion is overhaning the built-in support to much. Leaving a less than ideal result 😅

![fix](https://user-images.githubusercontent.com/41635644/204285341-952d8f05-8946-4aed-a6c7-960e4de4b587.png)

I've widened the support with 1mm in total so that it's fully supporting everything:
https://mega.nz/folder/sV8TGSID#w6U6yWF4Cdu5oPiOOKkUmg

**Comment by jlas1** [comment]
Solved, thanks
