### ISSUE TITLE
Non standard MGN12H carriage

### ISSUE THREAD

**Issue by ManiekJG** [majarspeed/Unklicky#13]
I would love to switch to VORON TAP using Unklicky as I can't get a hold of optical sensor. However I have an issue with my linear rail carriage. I have a RobotDigg MGN12H which has plastik / non conductive part where the screws are supposed to make contact (half of carriage thickness). Would there be any chance for a version for these kinds of carriage?

**Comment by 0x3333** [comment]
Just add an Adhesive Conductive Tape to it.

[Like this](https://www.aliexpress.com/item/1005003118020966.html)

**Comment by majarspeed** [comment]
No redesign planned right now.
