### ISSUE TITLE
Mistake or intendent higher face?

### ISSUE THREAD

**Issue by tomdelahaba** [majarspeed/Unklicky#20]
Hello, I have to (unfortunately) modify the step for use of 5x3 magnets (6x3 are very hard to buy in here and I do not want to wait for the magnets to arrive from China). So I am about to modify the model, unfortunately I see that one magnet (the top one on the face where these 3 magnets are, so inside one of them, the face is a little bit higher then I would suppose. Is it meant to be like this or is it just some small mistake? That face seems to be extruded towards the top by 0.1mm

![image](https://github.com/majarspeed/Unklicky/assets/89455229/ca48c212-edcc-43d0-9273-142c7638380b)

Another "question" I would have is, the holes for magnets seems to be 2.8mm deep, while magnets are 3mm. Is it mean to be like that so the magnets overflow the top face?

**Comment by majarspeed** [comment]
I believe we spoke on discord but yes this is as intended. 2 magnets get wires under them and one does not this is done to attempt to level as best I can when that is done.
