### ISSUE TITLE
Corrupted STEP files?

### ISSUE THREAD

**Issue by TheHumbleOne1** [majarspeed/Unklicky#6]
I cant open STEP files for BFP and also Unklicky/Unklicky_Probes/Unklicky/CAD/
I suspect files might be corrupted? I am using F360.
I also can't open them with "online step viewers".

**Comment by TheHumbleOne1** [comment]
.STL Files also seem to be corrupted

**Comment by jlas1** [comment]
Hello, i checked the files, i can open them, and you can check that github STL viewer also can display them.
Maybe they are getting corrupted when you save them?

**Comment by TheHumbleOne1** [comment]
Hi, I just checked again. If I right clicked and saved file, it didn't work. But when I opened stl preview and downloaded or saved "raw" step, it worked as it should. Thank you again for helping me and thank you sir for releasing this project, I'm grateful.

**Comment by jlas1** [comment]
it's mostly @majarspeed project, i am just helping along :-) but thanks.
